name: CI-CD Pipeline

on:
  push:
    branches:
      - master
  workflows_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/backend ./backend
          docker push ${{ secrets.DOCKER_USER_NAME }}/backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/frontend ./frontend
          docker push ${{ secrets.DOCKER_USER_NAME }}/frontend
